baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'victorcoscolin'
theme = 'ficurinia'

[params]

    logo = "/static/logo.svg"
    favicon = "/static/favicon.png"
    faviconIco = "/static/favicon.ico"
    appletouch = "/static/apple-touch-icon.png"
    svgicon = "/static/logo.svg"
    icon512 = "/static/icon512.png"
